capture:
  time-seconds: 15

messages:
  prefix: "&6[Outpost] "
  captured: "&a%player% has captured the outpost!"
  ended: "&6%player% won the outpost!"

bossbars:
  timer: "&6Outpost ends in &e%time%"
  capture: "&aCapturing Outpost &7(%progress%%)"

end-commands:
  - "eco give %player% 1000"
